### ISSUE TITLE
Isn't the model and its weights supposed to be publicly available?

### ISSUE THREAD

**Issue by Elpaggio** [gonglinyuan/ast_t5#1]
This is from https://paperswithcode.com/paper/ast-t5-structure-aware-pretraining-for-code
"Our code and model are publicly available at https://github.com/gonglinyuan/ast_t5."

**Comment by gonglinyuan** [comment]
Sorry we were trying to convert the model checkpoint to the Huggingface format. The model checkpoint is now available at Huggingface model hub: https://huggingface.co/gonglinyuan/ast_t5_base
Thank you for your interest in AST-T5

**Comment by Elpaggio** [comment]
Sounds great, I think it is a very interesting model and I will try it out
as soon as I have the time for it. Keep up the exiting and to me almost
thrilling work you are doing!

lør. 10. feb. 2024 02.30 skrev Gong Linyuan ***@***.***>:
